### ISSUE TITLE
scammer

### ISSUE THREAD

**Issue by R7flex** [kenn-notation/Valorant-External#15]
stop pasting offset from unknowncheats
u are using wrong offset on bones lol
stop scamming peoples

**Comment by kenn-notation** [comment]
retarded turkish skid pasting my source and barking? stfu you begged me for everything and cried in dms every single day

**Comment by R7flex** [comment]
lol im not pasting your source i made 4 months ago stop please scamming peoples and pasting data ptr from busy10 lol

**Comment by Pinguu-dev** [comment]
funny i added the false bone offsets ^^
